apiVersion: app/v1
      kind: Deployment
metadata: 
    name: deployment_my-nginx
spec: 
  replicas: 4
    template:
      metadata:
        labels:
          app: my-nginx
  
  spec:
    containers:
      name: nginx
      image: nginx
      ports:
         -containerPort: 80
selector:
    match labels:
       app: my-nginx